{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.10.0.aar",
          "url": "media3-decode-opus-1.10.0.aar",
          "size": 524524,
          "sha512": "30690215281d7e4c439f06f89b59ae5c8944a682e31e70fd99894f66899f757e97c98c036570f2f044b1032732fe25e0abac0b363acbf734f894956446bd336d",
          "sha256": "1f29afc2b7922f76ede1225f47e5a37ca95409de3088ad17a5b91dab0f3a4347",
          "sha1": "aa31e82f94159b53cb0db2fb8f1553591e728d13",
          "md5": "91fa8bc78e20d3445acd5b1c9a382c74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.10.0.aar",
          "url": "media3-decode-opus-1.10.0.aar",
          "size": 524524,
          "sha512": "30690215281d7e4c439f06f89b59ae5c8944a682e31e70fd99894f66899f757e97c98c036570f2f044b1032732fe25e0abac0b363acbf734f894956446bd336d",
          "sha256": "1f29afc2b7922f76ede1225f47e5a37ca95409de3088ad17a5b91dab0f3a4347",
          "sha1": "aa31e82f94159b53cb0db2fb8f1553591e728d13",
          "md5": "91fa8bc78e20d3445acd5b1c9a382c74"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.10.0-sources.jar",
          "url": "media3-decode-opus-1.10.0-sources.jar",
          "size": 9476,
          "sha512": "2a6e5e7c2d26d570fa0687500303b43c8028976c89f54083a60ded136177dc51a34024678fbd40483d14beece91991e85e5c887ec1aa0e1ac34f7f2652d1e8df",
          "sha256": "6a1430f296eb49471db68bc7ad151e4e792e9b829232844b4e83aa3140a30c1d",
          "sha1": "03c6307bc9a42a3233e5f8505c43325bf322fb1c",
          "md5": "fe147fe60e03c9f3ca3e6671a1d9e6e7"
        }
      ]
    }
  ]
}
