{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-transformer",
    "version": "1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-transformer-1.11.1.aar",
          "url": "media3-transformer-1.11.1.aar",
          "size": 505538,
          "sha512": "264d60472248a1d976ad4a69ea50faabb75d68aad1534ebadc941bd787996d7e59837977f99a4ef0e3dbd93d3c4b83dfad446094b1e61481040fda7402c75c2f",
          "sha256": "78cfdd2df0f07a1fbb1b1db55ed7f7ea673147d651b66d2f2e804ac63117a18e",
          "sha1": "2489772a2b818d9767ccf96ed254b41ead9dae66",
          "md5": "cece46a111fcd82212eab24f92f470ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.11.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-transformer-1.11.1.aar",
          "url": "media3-transformer-1.11.1.aar",
          "size": 505538,
          "sha512": "264d60472248a1d976ad4a69ea50faabb75d68aad1534ebadc941bd787996d7e59837977f99a4ef0e3dbd93d3c4b83dfad446094b1e61481040fda7402c75c2f",
          "sha256": "78cfdd2df0f07a1fbb1b1db55ed7f7ea673147d651b66d2f2e804ac63117a18e",
          "sha1": "2489772a2b818d9767ccf96ed254b41ead9dae66",
          "md5": "cece46a111fcd82212eab24f92f470ff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-transformer-1.11.1-sources.jar",
          "url": "media3-transformer-1.11.1-sources.jar",
          "size": 338874,
          "sha512": "461d6b00425f2cf1375fd043b30b2aa57488e5956dbe3a9febe05d349429cccd89c6d25f02538398065fa603b440696dea4b80e7d8ee9c85cac1b4e1fa58cf6f",
          "sha256": "876a3b2ab33638fdef57d085afdbb63b110b8d8c2ba970e9c32ff25589d0e446",
          "sha1": "12dc7cbd20120fb3105dafa264a347cd232ea604",
          "md5": "6f64a0f24c130154f02b470900ff7c23"
        }
      ]
    }
  ]
}
