{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-effect",
    "version": "1.11.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.11.1.aar",
          "url": "media3-effect-1.11.1.aar",
          "size": 402182,
          "sha512": "041ab461583901b0af4e698b7e0a1450a5282721ee1d5657c25d4db929362f5086f165211b95aa3825135d4d1bba543530141e2136a816ec3b904e6b22e4c3f0",
          "sha256": "38fd511096fadee47c63fadbe19de425bec3f3247fd98a14875aed5984f8d4fa",
          "sha1": "f3366da44c09e46c60bd0dcceb74987c96bbdf59",
          "md5": "8bfe2344e46c901d3d15df782d3be361"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-guava",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-effect-1.11.1.aar",
          "url": "media3-effect-1.11.1.aar",
          "size": 402182,
          "sha512": "041ab461583901b0af4e698b7e0a1450a5282721ee1d5657c25d4db929362f5086f165211b95aa3825135d4d1bba543530141e2136a816ec3b904e6b22e4c3f0",
          "sha256": "38fd511096fadee47c63fadbe19de425bec3f3247fd98a14875aed5984f8d4fa",
          "sha1": "f3366da44c09e46c60bd0dcceb74987c96bbdf59",
          "md5": "8bfe2344e46c901d3d15df782d3be361"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-effect-1.11.1-sources.jar",
          "url": "media3-effect-1.11.1-sources.jar",
          "size": 255898,
          "sha512": "b2efe6b60dd94ea0f9af207306c082373cb32494abc4050b23653ee0bf716d3829b2ec5f81e339dc42e54028257882e828bba1883c505d27dd25a927fd44af0f",
          "sha256": "a452414ffe8dbc89bf7958120694e061603babb919517b13b79849a01a91685d",
          "sha1": "58e81972cdcc62f2d21559f80c7997a2ea058cc5",
          "md5": "fcbc625f2cc0895ed403c14f5bb48382"
        }
      ]
    }
  ]
}
