{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-flac",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.10.0.aar",
          "url": "media3-decode-flac-1.10.0.aar",
          "size": 578694,
          "sha512": "aadbae8b366c69f62f6fe81002ff5f99f930e68aed0d17d7e8a7e219c0cfa62bdf814bc8354f8781b09310bd8dead62d147a67a33a6c8431d77e4485b78c0a2b",
          "sha256": "0080118c26ec0f6cf5b3e61fcdd510cb31ef6c95acbff94884fb4a76ea9ded39",
          "sha1": "ad06f63aaf065fe316ecd8f8e3c3d1a45a24639f",
          "md5": "4b7cc859752e57c38ae40df2f22f4c52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-flac-1.10.0.aar",
          "url": "media3-decode-flac-1.10.0.aar",
          "size": 578694,
          "sha512": "aadbae8b366c69f62f6fe81002ff5f99f930e68aed0d17d7e8a7e219c0cfa62bdf814bc8354f8781b09310bd8dead62d147a67a33a6c8431d77e4485b78c0a2b",
          "sha256": "0080118c26ec0f6cf5b3e61fcdd510cb31ef6c95acbff94884fb4a76ea9ded39",
          "sha1": "ad06f63aaf065fe316ecd8f8e3c3d1a45a24639f",
          "md5": "4b7cc859752e57c38ae40df2f22f4c52"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-flac-1.10.0-sources.jar",
          "url": "media3-decode-flac-1.10.0-sources.jar",
          "size": 15748,
          "sha512": "ace6d2a23a3ac31f89c72e99fa5e525e1dd02184583e2260ae39c102b8f3bbc891ae90e58e640e3e1a9bbc84511366521732ffe6edab21a47bb3ebc904e92e74",
          "sha256": "636547d168b74eb6dde49727aa1b5430eb79b5b86cc77808dd9aaa44dfa948dc",
          "sha1": "648f0d2d5ae45d632506a44abcc31d234c370b97",
          "md5": "26cc69a7600a7b8a9561233647815276"
        }
      ]
    }
  ]
}
