{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-opus",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.8.0.aar",
          "url": "media3-decode-opus-1.8.0.aar",
          "size": 511707,
          "sha512": "631f63382d54609b9b84d9baa24cb6ad90b19ec8913fe6f2064011bf42f7366afc826a3af4ccad1411698a468423ba3d345f43a360145b20f8d90dad3c488de8",
          "sha256": "dfd497a56de21e0fee99c9510a97e758708234f452a8042816486489998b861f",
          "sha1": "e0a12141cddea8dc4eea538a4cfd6714303afdda",
          "md5": "7abd9f3806c66eaa9c1231e98a48d703"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-opus-1.8.0.aar",
          "url": "media3-decode-opus-1.8.0.aar",
          "size": 511707,
          "sha512": "631f63382d54609b9b84d9baa24cb6ad90b19ec8913fe6f2064011bf42f7366afc826a3af4ccad1411698a468423ba3d345f43a360145b20f8d90dad3c488de8",
          "sha256": "dfd497a56de21e0fee99c9510a97e758708234f452a8042816486489998b861f",
          "sha1": "e0a12141cddea8dc4eea538a4cfd6714303afdda",
          "md5": "7abd9f3806c66eaa9c1231e98a48d703"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-opus-1.8.0-sources.jar",
          "url": "media3-decode-opus-1.8.0-sources.jar",
          "size": 9397,
          "sha512": "7a0e31307fea6ead2a3e8e04edf5ab2594c1fa04007a5fcace3f2385e1e1ab8f537b498485e5f5f2a57705a66a64a88b3dab098de1f33dd41b26a22ec80346fd",
          "sha256": "c240deb746e60f92a69e0a9a4aa0da566b180286b3f24f282f59aa0c9266da4a",
          "sha1": "0c6df33ba6bbd2094f3c3e089dec97195b76c447",
          "md5": "caa1fa2425ba4ae79ca78c7ea320ecd2"
        }
      ]
    }
  ]
}
