{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-iamf",
    "version": "1.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.8.0.aar",
          "url": "media3-decode-iamf-1.8.0.aar",
          "size": 420770,
          "sha512": "ce395ef7ae0c5fecbb173f29a727ebf7923b7a3c22b06d7a864c098e6279bfa53b6feabfd62576279174246551003f1cdc28ecc5773d201135b5015b13d81af9",
          "sha256": "d45e2562fde8580d532f925a3b9679f3d1028af2b9b58674baab01d356096d07",
          "sha1": "53acba2574cebc2cb45e38b6211c7f8fe0ff10b5",
          "md5": "06928c9bd71dff7c73dfd4221f9a7169"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.8.0.aar",
          "url": "media3-decode-iamf-1.8.0.aar",
          "size": 420770,
          "sha512": "ce395ef7ae0c5fecbb173f29a727ebf7923b7a3c22b06d7a864c098e6279bfa53b6feabfd62576279174246551003f1cdc28ecc5773d201135b5015b13d81af9",
          "sha256": "d45e2562fde8580d532f925a3b9679f3d1028af2b9b58674baab01d356096d07",
          "sha1": "53acba2574cebc2cb45e38b6211c7f8fe0ff10b5",
          "md5": "06928c9bd71dff7c73dfd4221f9a7169"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-iamf-1.8.0-sources.jar",
          "url": "media3-decode-iamf-1.8.0-sources.jar",
          "size": 6995,
          "sha512": "8d93a1867e428598e317e15070e0e7b1a04d512de3c6917ae743c4cbc4ff02fb248694fb5077b985cea4da0b53ef831259847c08c9a9fff9ed8b933daa24e2ca",
          "sha256": "0e0e792b5e1a33854e269ad6171971564093ea4e6c757ea89d4cf03db2fed642",
          "sha1": "c656585a0c0e2da9f165e131d0b447417341361e",
          "md5": "924f44af8228b56ad704ce68123ab97b"
        }
      ]
    }
  ]
}
