{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-av1",
    "version": "1.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.9.0.aar",
          "url": "media3-decode-av1-1.9.0.aar",
          "size": 12668,
          "sha512": "bd649281aa87558f8bacaa823e7fe247c1743c10ede67842fdb4a50a38c11e4362017591cccd4cbad4c678757cfd2ea847b355b60f43f58a338ab9bd205a240f",
          "sha256": "76f40181380152654cdd6165e8cb1bbf56d7235e4f2680b927b95dad0d16fc91",
          "sha1": "2e5dbca2997d5994a96ca1bac2e59c5162722b24",
          "md5": "f436c92a6af2da86a573eaf24cf82500"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.9.0.aar",
          "url": "media3-decode-av1-1.9.0.aar",
          "size": 12668,
          "sha512": "bd649281aa87558f8bacaa823e7fe247c1743c10ede67842fdb4a50a38c11e4362017591cccd4cbad4c678757cfd2ea847b355b60f43f58a338ab9bd205a240f",
          "sha256": "76f40181380152654cdd6165e8cb1bbf56d7235e4f2680b927b95dad0d16fc91",
          "sha1": "2e5dbca2997d5994a96ca1bac2e59c5162722b24",
          "md5": "f436c92a6af2da86a573eaf24cf82500"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.9.0-sources.jar",
          "url": "media3-decode-av1-1.9.0-sources.jar",
          "size": 10338,
          "sha512": "53ba0e3a58acbb3d5e1c8766e58e0f72787fe6b1ab8371bfaa0bc81867269d7f573a4107f7cf576c07d00efe3fe4118de3654ae3526c5196f88d19e8dbbf2f0a",
          "sha256": "33284308e55d631071ec2834f84b195500a44fe7a6c9d13dd4d0f8ef11614e0c",
          "sha1": "df9b55fd0d6c081747562a24ba91e1711ffa94c2",
          "md5": "e9f6077c1100cd645389b9dfe841d5c0"
        }
      ]
    }
  ]
}
