{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-av1",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.10.0.aar",
          "url": "media3-decode-av1-1.10.0.aar",
          "size": 12668,
          "sha512": "cbe026aa4256a4610b28a30f1cc74e1a583b00a607c4c50938a60db0074ede6ccfb421b273320466ac81126034260e42d2be8a348de250fc1d138ea4753f3d8c",
          "sha256": "021329e2d2fe7d321e09c69e74622e905d54d82b2df3cc842a7d0bc78379935f",
          "sha1": "e9a5c0d65e2743eedc8b0bd0d104ab3a9337f737",
          "md5": "39e7a59002b43057b242e1773325b91e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-av1-1.10.0.aar",
          "url": "media3-decode-av1-1.10.0.aar",
          "size": 12668,
          "sha512": "cbe026aa4256a4610b28a30f1cc74e1a583b00a607c4c50938a60db0074ede6ccfb421b273320466ac81126034260e42d2be8a348de250fc1d138ea4753f3d8c",
          "sha256": "021329e2d2fe7d321e09c69e74622e905d54d82b2df3cc842a7d0bc78379935f",
          "sha1": "e9a5c0d65e2743eedc8b0bd0d104ab3a9337f737",
          "md5": "39e7a59002b43057b242e1773325b91e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-av1-1.10.0-sources.jar",
          "url": "media3-decode-av1-1.10.0-sources.jar",
          "size": 10338,
          "sha512": "53ba0e3a58acbb3d5e1c8766e58e0f72787fe6b1ab8371bfaa0bc81867269d7f573a4107f7cf576c07d00efe3fe4118de3654ae3526c5196f88d19e8dbbf2f0a",
          "sha256": "33284308e55d631071ec2834f84b195500a44fe7a6c9d13dd4d0f8ef11614e0c",
          "sha1": "df9b55fd0d6c081747562a24ba91e1711ffa94c2",
          "md5": "e9f6077c1100cd645389b9dfe841d5c0"
        }
      ]
    }
  ]
}
