{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-decode-iamf",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.10.0.aar",
          "url": "media3-decode-iamf-1.10.0.aar",
          "size": 12540,
          "sha512": "719cd3db24470bcd8ec5e2ef986aac9ab382f63379fb21705e2bef1c54482a8c7dc28150f58d43e94204b93b1d97e372930a3d526cac6b952cc8afcba932709d",
          "sha256": "e5497a363bd6cdfe4b6383ebe01b70d63328b12a0c9d45468ad212c21c811fea",
          "sha1": "48323cdcba29f16e960aaddf427ae5b8fc97b8cf",
          "md5": "4ccda5da19e499c07a8858e37b5546a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "media3-decode-iamf-1.10.0.aar",
          "url": "media3-decode-iamf-1.10.0.aar",
          "size": 12540,
          "sha512": "719cd3db24470bcd8ec5e2ef986aac9ab382f63379fb21705e2bef1c54482a8c7dc28150f58d43e94204b93b1d97e372930a3d526cac6b952cc8afcba932709d",
          "sha256": "e5497a363bd6cdfe4b6383ebe01b70d63328b12a0c9d45468ad212c21c811fea",
          "sha1": "48323cdcba29f16e960aaddf427ae5b8fc97b8cf",
          "md5": "4ccda5da19e499c07a8858e37b5546a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-decode-iamf-1.10.0-sources.jar",
          "url": "media3-decode-iamf-1.10.0-sources.jar",
          "size": 10272,
          "sha512": "87a2f249be87db69ea205f7ade2ae7679b7692a30e9dd0b502d5469c124de88bb3c0a68d815b449bd8af36cf945817be13fdc41c891725e3ee93906754346002",
          "sha256": "cdb22503a1506ae59b5d17f6129b08f42aa5085127b02c25d09ea264e57ad47e",
          "sha1": "634607c02ce0bfba6543a372dc6584b516cf4ab4",
          "md5": "539132c136a87cb5c9df6255e8309116"
        }
      ]
    }
  ]
}
